version: '3'

services:
  proxy:
    build:
      context: ../build/proxy
      dockerfile: Dockerfile
    ports:
      - 3000:80
      - 8080:8080
    networks:
      - base
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  characters:
    build:
      context: ../
      dockerfile: build/package/Dockerfile
      args:
        - app=characters
    networks:
      - base
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.characters.rule=Host(`localhost`) && PathPrefix(`/api/v1/characters`)
      - traefik.http.routers.characters.entrypoints=http
      - traefik.http.services.characters.loadbalancer.server.port=3001

  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_DB: "go-micro"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/data"
    networks:
      - base
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/data"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6.15
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - base
    restart: always

volumes:
  postgres: {}
  pgadmin: {}

networks:
  base:
